language: objective-c
osx_image: xcode8.3
before_install: true
install: true
before_script:
 - chmod +x ./script/build
script:
  - script/build
xcode_project: Feathers.xcodeproj
matrix:
  include:
    - xcode_scheme: Feathers-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
    - script:
        - carthage build --no-skip-current --platform iOS --verbose
      env:
        - JOB=CARTHAGE-iOS
    - script:
      - gem install cocoapods
      - pod repo update --silent
      - travis_wait 30 pod lib lint Feathers.podspec
      env:
        - JOB=PODSPEC
